export default {
    Button: {
        raised: true,
        titleStyle: {
            color: '#fff',
        },
        primary: {
            backgroundColor: "#c4157e",
            borderRadius: 20,
            paddingLeft: 20,
            paddingRight: 20,
            marginLeft: 0,
            marginRight: 0,
            marginBottom: 15,
            shadowColor: '#a5a5a5',
            shadowOpacity: 0.9,
            elevation: 10,
            shadowRadius: 15,
            shadowOffset: { width: 10, height: 13 },
        },
        giftAdd: {
            backgroundColor: "#c4157e",
            borderRadius: 20,
            paddingLeft: 80,
            paddingRight: 80,
            marginLeft: 0,
            marginRight: 0,
            marginBottom: 15,
            shadowColor: '#a5a5a5',
            shadowOpacity: 0.9,
            elevation: 10,
            shadowRadius: 15,
            shadowOffset: { width: 10, height: 13 },
        },
        totalCostBasket: {
            position: 'absolute',
            bottom: 100,
            zIndex: 100,
            right: 140,
            justifyContent: 'center',
            alignItems: 'center',
            backgroundColor: "white",
            borderRadius: 20,
            paddingLeft: 20,
            paddingRight: 20,
            marginLeft: 0,
            marginRight: 0,
            marginBottom: 15,
            shadowColor: '#1b73d5',
            shadowOpacity: 0.9,
            elevation: 10,
            shadowRadius: 15,
            shadowOffset: { width: 10, height: 5 },
        }
    },
    Card: {
        containerStyle: {
            // raised: true,
            marginTop: 20,
            marginBottom: 20,
            marginLeft: 0,
            marginRight: 0,
            shadowColor: "#000",
            shadowOffset: {
                width: 0,
                height: 2,
            },
            shadowOpacity: 0.25,
            shadowRadius: 3.84,
            elevation: 10

        }
    },
    colors: {
        primary: "#c4157e",
        secondary: "#E8249A",
        grey0: '#393e42',
        grey1: '#43484d',
        grey2: '#5e6977',
        grey3: '#86939e',
        grey4: '#bdc6cf',
        grey5: '#e1e8ee',
        dkGreyBg: '#232323',
        greyOutline: '#bbb',
        searchBg: '#303337',
        disabled: '#dadee0',
        white: '#ffffff',
        error: '#ff190c',
    }
}